# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-batch-users:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Uploads to a batch of users
        id: get_batch_users
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          num: 1
          prefix: fvn
          days: 1
      - name: Print the status
        run: echo "${{steps.get_batch_users.outputs.result}}"
